import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { loadGithub } from "./github.mjs";
import { loadIcons } from "./icons.mjs";
import { C, buttonSvg, heroSvg, historySvg, resolveSpec, stackSvg, suiteSvg } from "./svg.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const at = (...p) => join(root, ...p);

const profile = JSON.parse(await readFile(at("profile.json"), "utf8"));
await mkdir(at("assets"), { recursive: true });
await mkdir(at("data"), { recursive: true });

const gh = process.env.DEMO ? demoData() : await loadGithub(profile.handle, at("data/github.json"));
const slugs = profile.stack.flatMap((g) => g.items.map((i) => i.icon)).filter(Boolean);
const icons = await loadIcons(slugs, at("data/icons.json"));
const runDate = gh?.fetchedAt ? gh.fetchedAt.slice(0, 10) : "awaiting first CI run";

const repo = `https://github.com/${profile.handle}/${profile.handle}`;
const links = {
  run: profile.site,
  recruiter: `${profile.site}#recruiter`,
  linkedin: profile.links.linkedin,
  website: profile.links.website,
  email: `mailto:${profile.links.email}`,
  hire: `${repo}/issues/new?template=hire.yml`,
  bug: `${repo}/issues/new?template=bug.yml`,
};

const buttons = {
  run: { label: "Run me live", glyph: "▶", accent: C.green, primary: true },
  recruiter: { label: "Recruiter mode", glyph: "◧", accent: C.blue },
  linkedin: { label: "LinkedIn", glyph: "in", accent: "#0A84FF" },
  website: { label: "Website", glyph: "⌘", accent: C.cyan },
  email: { label: "Email", glyph: "@", accent: C.amber },
  hire: { label: "Feature request: hire me", glyph: "+", accent: C.green },
  bug: { label: "File a bug against me", glyph: "!", accent: C.red },
};

const files = {
  "assets/hero.svg": heroSvg(profile),
  "assets/suite.svg": suiteSvg(profile, gh, runDate),
  "assets/stack.svg": stackSvg(profile, icons),
  "assets/history.svg": historySvg(gh),
  ...Object.fromEntries(Object.entries(buttons).map(([k, b]) => [`assets/btn-${k}.svg`, buttonSvg(b)])),
  "README.md": readme(),
  "docs/data.js": `// generated by scripts/build.mjs from profile.json\nwindow.PROFILE = ${JSON.stringify(
    {
      ...profile,
      github: gh ? { ...gh, weeks: undefined } : null,
      suite: resolveSpec(profile, gh),
      icons: Object.fromEntries(slugs.filter((s) => icons[s]).map((s) => [s, icons[s]])),
      links,
      runDate,
    },
    null,
    2,
  )};\n`,
};

for (const [path, content] of Object.entries(files)) {
  await mkdir(dirname(at(path)), { recursive: true });
  await writeFile(at(path), content);
}
console.log(`built ${Object.keys(files).length} files · github data: ${gh ? runDate : "none"}`);

function btn(key, height = 44) {
  return `<a href="${links[key]}"><img src="assets/btn-${key}.svg" height="${height}" alt="${buttons[key].label}"></a>`;
}

function readme() {
  const current = profile.experience.find((e) => e.current);
  const past = profile.experience.filter((e) => !e.current);
  const stackRow = (group) =>
    profile.stack.find((g) => g.group === group)?.items.map((i) => i.name).join(" · ") ?? "";
  const q = (s) => `'${s.replace(/'/g, "\\'")}'`;
  const config = [
    `// ${profile.handle.toLowerCase()}.config.ts`,
    `export default defineConfig({`,
    `  name: ${q(profile.name)},`,
    `  role: ${q(`${current.role} @ ${current.company}`)},`,
    `  previously: [${past.map((e) => q(`${e.role} @ ${e.company}`)).join(", ")}],`,
    `  projects: [`,
    ...profile.stack.map((g) => `    { name: ${q(g.group.toLowerCase())}, use: [${g.items.map((i) => q(i.name)).join(", ")}] },`),
    `  ],`,
    `  exploring: [`,
    ...profile.focus.map((f) => `    ${q(f)},`),
    `  ],`,
    `  retries: 0, // flaky tests get fixed, not retried`,
    `  reporter: [['list'], ['hire-me', { open: 'always' }]],`,
    `});`,
  ].join("\n");

  return `<!-- Generated by scripts/build.mjs from profile.json. Edit profile.json, not this file. -->
<div align="center">

<a href="${links.run}"><img src="assets/hero.svg" width="100%" alt="${profile.name}, ${current.role} at ${current.company}"></a>

${btn("run")} ${btn("recruiter")} ${btn("linkedin")} ${btn("website")} ${btn("email")}

</div>

<br>

<img src="assets/suite.svg" width="100%" alt="${profile.name} test run">

<details>
<summary><b>👔 Recruiter? Here's the 30-second version</b></summary>
<br>

> ${profile.summary}

| | |
|---|---|
| **Role** | ${current.role} @ [${current.company}](${current.url}) |
${past.map((e) => `| **Previously** | ${e.role} @ [${e.company}](${e.url}) |`).join("\n")}
| **Testing** | ${stackRow("Testing")} |
| **Languages** | ${stackRow("Languages")} |
| **CI / Cloud** | ${stackRow("CI / Cloud")} |
| **Now exploring** | ${profile.focus.join(" · ")} |
| **Contact** | [LinkedIn](${links.linkedin}) · [Email](${links.email}) · [Open a hire request](${links.hire}) · [Printable résumé](${links.recruiter}) |

</details>

<details>
<summary><b>🧑‍💻 Developer? Read the config</b></summary>
<br>

\`\`\`ts
${config}
\`\`\`

</details>

<br>

<img src="assets/stack.svg" width="100%" alt="Tech stack">

<img src="assets/history.svg" width="100%" alt="Contribution history">

<div align="center">

### Found a bug in me?

${btn("bug", 40)} ${btn("hire", 40)}

<sub>This profile is a test suite. It is generated from <a href="profile.json"><code>profile.json</code></a> and re-runs every night in GitHub Actions.<br>
Fork it, edit one file, and ship your own. See <a href="TEMPLATE.md"><code>TEMPLATE.md</code></a>.</sub>

</div>
`;
}

function demoData() {
  const weeks = [];
  const start = Date.UTC(2025, 8, 21);
  for (let w = 0; w < 53; w++) {
    const days = [];
    for (let d = 0; d < 7; d++) {
      const i = w * 7 + d;
      const v = Math.max(0, Math.round(Math.sin(i / 9) * 4 + Math.sin(i / 2.3) * 3 + (i % 11 === 0 ? -6 : 1)));
      days.push({ date: new Date(start + i * 864e5).toISOString().slice(0, 10), count: v });
    }
    weeks.push(days);
  }
  return {
    fetchedAt: new Date().toISOString(),
    contributions: weeks.flat().reduce((a, d) => a + d.count, 0),
    longestStreak: 23, currentStreak: 6, repos: 18, stars: 41, followers: 57, pullRequests: 212,
    languages: [
      { name: "TypeScript", color: "#3178c6", pct: 41.2 }, { name: "JavaScript", color: "#f1e05a", pct: 22.5 },
      { name: "Java", color: "#b07219", pct: 14.1 }, { name: "Python", color: "#3572A5", pct: 12.9 },
      { name: "HTML", color: "#e34c26", pct: 5.8 }, { name: "CSS", color: "#563d7c", pct: 3.5 },
    ],
    weeks,
  };
}
