import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { loadGithub } from "./github.mjs";
import { loadIcons } from "./icons.mjs";
import { descentSvg } from "./descent.mjs";
import { C, buttonSvg, heroSvg, historySvg, resolveSpec, stackSvg, suiteSvg } from "./svg.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const at = (...p) => join(root, ...p);

const profile = JSON.parse(await readFile(at("profile.json"), "utf8"));
await mkdir(at("assets"), { recursive: true });
await mkdir(at("data"), { recursive: true });

// In Actions the repository decides whose profile this is, so a copied repo never shows the original author's data.
const repoSlug = process.env.GITHUB_REPOSITORY ?? `${profile.handle}/${profile.handle}`;
const [repoOwner, repoName] = repoSlug.split("/");
if (repoOwner.toLowerCase() !== profile.handle.toLowerCase()) {
  console.warn(`profile.json handle "${profile.handle}" doesn't match repo owner "${repoOwner}"; using "${repoOwner}". Update "handle" in profile.json.`);
  profile.handle = repoOwner;
}
const pagesSite = `https://${repoOwner.toLowerCase()}.github.io/${repoName}/`;
if (!profile.site || (profile.site.includes(".github.io") && !profile.site.includes(`//${repoOwner.toLowerCase()}.github.io`))) {
  profile.site = pagesSite;
}

const gh = process.env.DEMO ? demoData() : await loadGithub(profile.handle, at("data/github.json"));
const slugs = profile.stack.flatMap((g) => g.items.map((i) => i.icon)).filter(Boolean);
const icons = await loadIcons(slugs, at("data/icons.json"));
const runDate = gh?.fetchedAt ? gh.fetchedAt.slice(0, 10) : "awaiting first CI run";

const repo = `https://github.com/${repoSlug}`;
const links = {
  run: profile.site,
  recruiter: `${profile.site}#recruiter`,
  linkedin: profile.links.linkedin,
  website: profile.links.website,
  email: `mailto:${profile.links.email}`,
  hire: `${repo}/issues/new?template=hire.yml`,
  bug: `${repo}/issues/new?template=bug.yml`,
};

const buttons = {
  run: { label: "Run me live", glyph: "▶", accent: C.green, primary: true },
  recruiter: { label: "Recruiter mode", glyph: "◧", accent: C.blue },
  linkedin: { label: "LinkedIn", glyph: "in", accent: "#0A84FF" },
  website: { label: "Website", glyph: "⌘", accent: C.cyan },
  email: { label: "Email", glyph: "@", accent: C.amber },
  hire: { label: "Feature request: hire me", glyph: "+", accent: C.green },
  bug: { label: "File a bug against me", glyph: "!", accent: C.red },
};

const theme = profile.theme === "spec" ? "spec" : "descent";
if (theme === "descent") {
  Object.assign(buttons.run, { label: "Explore interactively" });
  Object.assign(buttons.recruiter, { label: "Résumé" });
  Object.assign(buttons.hire, { label: "Hire me" });
  Object.assign(buttons.bug, { label: "Leave feedback" });
}

const files = {
  ...(theme === "descent"
    ? { "assets/descent.svg": descentSvg(profile, gh) }
    : {
        "assets/hero.svg": heroSvg(profile),
        "assets/suite.svg": suiteSvg(profile, gh, runDate),
        "assets/stack.svg": stackSvg(profile, icons),
        "assets/history.svg": historySvg(gh),
      }),
  ...Object.fromEntries(Object.entries(buttons).map(([k, b]) => [`assets/btn-${k}.svg`, buttonSvg(b, theme)])),
  "README.md": readme(),
  "docs/index.html": pageHead(await readFile(at("docs/index.html"), "utf8")),
  ".github/ISSUE_TEMPLATE/hire.yml": hireForm(),
  ".github/ISSUE_TEMPLATE/bug.yml": bugForm(),
  "docs/data.js": `// generated by scripts/build.mjs from profile.json\nwindow.PROFILE = ${JSON.stringify(
    {
      ...profile,
      github: gh ? { ...gh, weeks: undefined } : null,
      suite: resolveSpec(profile, gh),
      icons: Object.fromEntries(slugs.filter((s) => icons[s]).map((s) => [s, icons[s]])),
      links,
      runDate,
    },
    null,
    2,
  )};\n`,
};

for (const [path, content] of Object.entries(files)) {
  await mkdir(dirname(at(path)), { recursive: true });
  await writeFile(at(path), content);
}
console.log(`built ${Object.keys(files).length} files · github data: ${gh ? runDate : "none"}`);

function pageHead(html) {
  const e = (v) => String(v).replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;");
  const title = e(`${profile.name} · readme.spec`);
  const desc = e(`${profile.name}, ${profile.title}. A profile you can run like a test suite.`);
  return html
    .replace(/<title>[^<]*<\/title>/, `<title>${title}</title>`)
    .replace(/(<meta name="description" content=")[^"]*/, `$1${desc}`)
    .replace(/(<meta property="og:title" content=")[^"]*/, `$1${title}`);
}

function firstName() {
  return profile.name.split(" ")[0];
}

function yamlStr(s) {
  return JSON.stringify(s);
}

function hireForm() {
  return `# Generated by scripts/build.mjs from profile.json.
name: ${yamlStr(`💼 Feature request: hire ${firstName()}`)}
description: Propose a role, a collaboration, or a project. This is the fastest way to reach me.
title: "[hire] "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for stopping by. Fill in what you can; nothing here is strictly required except a way to reach you.
        Heads-up: issues in this repo are **public**. If you'd rather keep details private, just leave a contact and I'll reach out.
  - type: input
    id: company
    attributes:
      label: Company / team
      placeholder: Acme Inc. · Platform Quality
  - type: dropdown
    id: kind
    attributes:
      label: What kind of request is this?
      options:
        - Full-time role
        - Contract / consulting
        - Open-source collaboration
        - Speaking / writing
        - Just saying hi
  - type: textarea
    id: details
    attributes:
      label: Acceptance criteria
      description: What would success look like? Role scope, stack, team size, anything useful.
      placeholder: |
        Given a team shipping fast,
        When ${firstName()} joins,
        Then flaky tests go to zero and releases get boring (the good kind).
  - type: input
    id: contact
    attributes:
      label: How can I reach you?
      placeholder: email, LinkedIn, or "reply here"
    validations:
      required: true
`;
}

function bugForm() {
  return `# Generated by scripts/build.mjs from profile.json.
name: ${yamlStr(`🐞 Bug report: found a bug in ${firstName()}`)}
description: Feedback, a typo on this profile, a hot take on testing, or anything else. Every report gets triaged.
title: "[bug] "
body:
  - type: markdown
    attributes:
      value: |
        You found a bug in the system under test. Nice catch.
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - cosmetic (typo, broken link, pixel off)
        - minor (feedback or suggestion)
        - major (strong opinion about testing)
        - blocker (we need to talk now)
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Open the profile
        2. Scroll to …
        3. See …
  - type: textarea
    id: expected
    attributes:
      label: Expected vs. actual
      placeholder: Expected … but instead …
`;
}

function btn(key, height = 44) {
  if (links[key].includes("[")) return "";
  return `<a href="${links[key]}"><img src="assets/btn-${key}.svg" height="${height}" alt="${buttons[key].label}"></a>`;
}

function readme() {
  const current = profile.experience.find((e) => e.current);
  const past = profile.experience.filter((e) => !e.current);
  const q = (s) => `'${s.replace(/'/g, "\\'")}'`;
  const config = [
    `// ${profile.handle.toLowerCase()}.config.ts`,
    `export default defineConfig({`,
    `  name: ${q(profile.name)},`,
    `  role: ${q(`${current.role} @ ${current.company}`)},`,
    `  previously: [${past.map((e) => q(`${e.role} @ ${e.company}`)).join(", ")}],`,
    `  projects: [`,
    ...profile.stack.map((g) => `    { name: ${q(g.group.toLowerCase())}, use: [${g.items.map((i) => q(i.name)).join(", ")}] },`),
    `  ],`,
    `  exploring: [`,
    ...profile.focus.map((f) => `    ${q(f)},`),
    `  ],`,
    `  retries: 0, // flaky tests get fixed, not retried`,
    `  reporter: [['list'], ['hire-me', { open: 'always' }]],`,
    `});`,
  ].join("\n");

  const recruiter = `<details>
<summary><b>👔 Recruiter? Here's the 30-second version</b></summary>
<br>

> ${profile.summary}

| | |
|---|---|
| **Role** | ${current.role} @ [${current.company}](${current.url}) |
${past.map((e) => `| **Previously** | ${e.role} @ [${e.company}](${e.url}) |`).join("\n")}
${profile.stack.map((g) => `| **${g.group}** | ${g.items.map((i) => i.name).join(" · ")} |`).join("\n")}
| **Now exploring** | ${profile.focus.join(" · ")} |
| **Contact** | ${[["LinkedIn", links.linkedin], ["Website", links.website], ["Email", links.email], ["Open a hire request", links.hire], ["Printable résumé", links.recruiter]].filter(([, u]) => !u.includes("[")).map(([t, u]) => `[${t}](${u})`).join(" · ")} |

</details>`;
  const developer = `<details>
<summary><b>🧑‍💻 Developer? Read the config</b></summary>
<br>

\`\`\`ts
${config}
\`\`\`

</details>`;
  const head = "<!-- Generated by scripts/build.mjs from profile.json. Edit profile.json, not this file. -->";

  if (theme === "descent") {
    return `${head}
<a href="${links.run}"><img src="assets/descent.svg" width="100%" alt="${profile.name}, ${current.role} at ${current.company}. An animated scene: a flock of starlings spells the name at dusk, a star atlas charts the skills, and repositories drift as glowing jellyfish above a seabed of contributions."></a>

<div align="center">

${btn("run")} ${btn("recruiter")} ${btn("linkedin")} ${btn("website")} ${btn("email")}

</div>

${recruiter}

${developer}

<div align="center">

<sub><i>This profile is alive.</i> The flock is the year's contributions, the constellations are the craft, the ring of months is the year's rhythm,<br>
each jellyfish is a repository (size = stars, glow = recent pushes), and the seabed is every day of work. The moon is tonight's.<br>
Regenerated hourly from live GitHub data. <a href="TEMPLATE.md">Make your own</a>.</sub>

${btn("bug", 40)} ${btn("hire", 40)}

</div>
`;
  }

  return `${head}
<div align="center">

<a href="${links.run}"><img src="assets/hero.svg" width="100%" alt="${profile.name}, ${current.role} at ${current.company}"></a>

${btn("run")} ${btn("recruiter")} ${btn("linkedin")} ${btn("website")} ${btn("email")}

</div>

<br>

<img src="assets/suite.svg" width="100%" alt="${profile.name} test run">

${recruiter}

${developer}

<br>

<img src="assets/stack.svg" width="100%" alt="Tech stack">

<img src="assets/history.svg" width="100%" alt="Contribution history">

<div align="center">

### Found a bug in me?

${btn("bug", 40)} ${btn("hire", 40)}

<sub>This profile is a test suite. It is generated from <a href="profile.json"><code>profile.json</code></a> and re-runs every hour in GitHub Actions.<br>
Fork it, edit one file, and ship your own. See <a href="TEMPLATE.md"><code>TEMPLATE.md</code></a>.</sub>

</div>
`;
}

function demoData() {
  const weeks = [];
  const start = Date.UTC(2025, 8, 21);
  for (let w = 0; w < 53; w++) {
    const days = [];
    for (let d = 0; d < 7; d++) {
      const i = w * 7 + d;
      const v = Math.max(0, Math.round(Math.sin(i / 9) * 4 + Math.sin(i / 2.3) * 3 + (i % 11 === 0 ? -6 : 1)));
      days.push({ date: new Date(start + i * 864e5).toISOString().slice(0, 10), count: v });
    }
    weeks.push(days);
  }
  return {
    fetchedAt: new Date().toISOString(),
    contributions: weeks.flat().reduce((a, d) => a + d.count, 0),
    longestStreak: 23, currentStreak: 6, repos: 18, stars: 41, followers: 57, pullRequests: 212,
    repoList: [
      { name: "SkillMeUp", stars: 2, lang: "TypeScript", color: "#3178c6", activity: 0.95 },
      { name: "PrakharMartand", stars: 0, lang: "JavaScript", color: "#f1e05a", activity: 1 },
      { name: "P7Martand", stars: 0, lang: "JavaScript", color: "#f1e05a", activity: 0.35 },
      { name: "OpenSourceHarness", stars: 0, lang: "TypeScript", color: "#3178c6", activity: 0.25 },
      { name: "reproRepo", stars: 0, lang: "Python", color: "#3572A5", activity: 0.5 },
    ],
    languages: [
      { name: "TypeScript", color: "#3178c6", pct: 41.2 }, { name: "JavaScript", color: "#f1e05a", pct: 22.5 },
      { name: "Java", color: "#b07219", pct: 14.1 }, { name: "Python", color: "#3572A5", pct: 12.9 },
      { name: "HTML", color: "#e34c26", pct: 5.8 }, { name: "CSS", color: "#563d7c", pct: 3.5 },
    ],
    weeks,
  };
}
